#pragma once

#include <grpcpp/grpcpp.h>
#include "raft.grpc.pb.h" // generated by cmake

#include <vector>
#include <string>
#include <map>

#include <mutex>
#include <thread>
#include <condition_variable>

using grpc::ServerContext;
using grpc::Status;

namespace raft_kv {
    enum class NodeState {
        FOLLOWER,
        CANDIDATE,
        LEADER
    };

    class RaftNode final : public RaftService::Service {
        public:
            RaftNode(int node_id, const std::map<int, std::string>& peer_addresses);
            ~RaftNode();

            // gRPC service implementation
            Status AppendEntries(ServerContext* context, const AppendEntriesRequest* request AppendEntriesResponse* response) override;
            Status RequestVote(ServerContext* context, const RequestVoteRequest* request, const RequestVoteResponse* response) override;

            Status Put(ServerContext* context, const PutRequest* request, PutResponse* response) override;
            Status Get(ServerContext* context, const GetRequest* request, GetResponse* response) override;

            // Start background election loop
            void Start();

        private:
            // Internal helpers
            void RunBackgroundLoop();
            void StartElection();
            void SendHeartbeats();
            int GetRandomTimeout();

            // State variables
            std::mutex mutex_;
            NodeState state_;
            int current_term_;
            int vote_for_;
            int my_id_;
            int leader_id_;

            // Log
            std::vector<LogEntry> log_;
            int commit_index_;
            int last_applied_;

            // Storage
            std::map<std::string, std::string> kv_store_;

            // Networking
            std::map<int, std::unique_ptr<RaftService::Stud>> peers_; // map peer id to stub

            // Threads and synchronization
            std::thread background_thread_; // timer
            std::condition_variable cv_; // wake up thread
            bool stop_flag_; //shut down gracefully
            std::chrono::time_point<std::chrono:steady_clock> last_election_time_;
    };
} // namespace raft_kv